############################################################
## STYLE-ONLY v1.6 S20-REFERENCE + EXACT COMPACT-LABEL FIX
## Built directly from the user's uploaded/running v1.2 script.
## Dense four-category facet axes use short display-only labels at 25 degrees,
## with locally smaller text and tighter line spacing.
## S17D uses the same compact category labels and a wrapped local title.
## S18C uses a two-line title to prevent clipping.
## Scientific inputs, thresholds, statistics, state definitions,
## analytical logic, numerical outputs, and outer figure canvas sizes are unchanged.
############################################################

## PUBLIC FIGURE STYLE CONTRACT
##   Internal analytical state IDs are unchanged.
##   Display labels are lowercase-first:
##     immune-defective/cold
##     myeloid–Treg immunosuppressive
##     tumor-dedifferentiation/stromal-remodeling
##     melanocytic differentiation
##   Fixed state palette:
##     #4DBBD5 / #00A087 / #E64B35 / #3C5488
##   Manuscript-facing figures use sans and the frozen S20-reference hierarchy;
##   base size is adapted to panel density (~11-12.5 pt), with local wrapping
##   for long state/category labels. White background, light major grid,
##   no minor grid, and black panel border are retained where applicable.
##   No numerical/statistical definition is changed by the style patch.


############################################################
## 22_Supplementary_Figures_S15_S19_CANONICAL_v1.0.3_LABEL_CASE_NORMALIZATION.R
##
## 21E PURPOSE
##   Rebuild Supplementary Figures S15-S19 from the frozen
##   canonical Primary Visium panel-source tables generated by
##   Script 21.
##
## REPORTING-ONLY CONTRACT
##   - no state rescoring
##   - no graph reconstruction
##   - no new permutation
##   - no residualization
##   - no threshold re-selection
##   - no biological reclassification
##
## OUTPUTS
##   results/figures/primary_visium_spatial/
##       Supplementary_Figure_S15.{pdf,jpg}
##       ...
##       Supplementary_Figure_S19.{pdf,jpg}
##       panels/*.pdf
##
## IMPORTANT INTERPRETIVE BOUNDARIES
##   - Fisher OR = descriptive effect size
##   - spot-level correlations = effect-size summaries
##   - empirical permutation P carries the spatial robustness layer
##   - S19 = humoral/TLS-like transcriptional context only
##   - no mature TLS / functional TLS / direct interaction claims
############################################################

rm(list = ls())
gc()
options(stringsAsFactors = FALSE)

project_dir <- Sys.getenv(
  "ICB_PROJECT_DIR",
  unset = "D:/ICB_resistance_project"
)

project_dir <- normalizePath(
  project_dir,
  winslash = "/",
  mustWork = TRUE
)

panel_root <- file.path(
  project_dir,
  "results",
  "tables",
  "primary_visium_spatial",
  "panel_sources"
)

reporting_root <- file.path(
  project_dir,
  "results",
  "reporting",
  "primary_visium_spatial"
)

decision_file <- file.path(
  reporting_root,
  "21D_reporting_rebuild_decision.csv"
)

figure_root <- file.path(
  project_dir,
  "results",
  "figures",
  "primary_visium_spatial"
)

panel_figure_root <- file.path(
  figure_root,
  "panels"
)

dir.create(
  figure_root,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  panel_figure_root,
  recursive = TRUE,
  showWarnings = FALSE
)

if (!requireNamespace("ggplot2", quietly = TRUE)) {
  stop("Package ggplot2 is required.", call. = FALSE)
}

if (!requireNamespace("grid", quietly = TRUE)) {
  stop("Base package grid is required.", call. = FALSE)
}

library(ggplot2)

############################################################
## 1. Helpers
############################################################

read_csv_exact <- function(file) {
  if (!file.exists(file)) {
    stop(
      "Missing canonical panel source: ",
      file,
      call. = FALSE
    )
  }

  utils::read.csv(
    file,
    check.names = FALSE,
    stringsAsFactors = FALSE
  )
}

safe_num <- function(x) {
  suppressWarnings(
    as.numeric(x)
  )
}

format_empirical_p <- function(p, n_perm = NA_integer_) {
  p <- safe_num(p)

  if (
    length(p) != 1L ||
    !is.finite(p)
  ) {
    return("P = NA")
  }

  if (
    is.finite(n_perm) &&
    n_perm > 0L &&
    abs(
      p -
      1 / (n_perm + 1)
    ) <
    1e-12
  ) {
    return(
      paste0(
        "empirical P = ",
        format(
          p,
          nsmall = 3
        ),
        " (",
        n_perm,
        " permutations)"
      )
    )
  }

  paste0(
    "P = ",
    format(
      p,
      digits = 3,
      scientific = TRUE
    )
  )
}

theme_visium <- function(base_size = 12.5, base_family = "sans") {
  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +
  ggplot2::theme(
    plot.title = element_text(face = "bold", size = base_size + 2.5, hjust = 0.5, color = "black"),
    plot.subtitle = element_text(size = base_size - 1, hjust = 0.5, color = "black"),
    axis.title = element_text(face = "bold", size = base_size, color = "black"),
    axis.title.y = element_text(face = "bold", size = base_size - 1, color = "black"),
    axis.title.x = element_text(face = "bold", size = base_size, color = "black"),
    axis.text = element_text(size = base_size - 1.5, color = "black"),
    legend.title = element_text(face = "bold", size = base_size, color = "black"),
    legend.text = element_text(size = base_size - 1.5, color = "black"),
    strip.text = element_text(face = "bold", size = base_size - 0.5, color = "black"),
    panel.grid.major = element_line(color = "#E8E8E8", linewidth = 0.30),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(color = "black", linewidth = 0.60),
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA)
  )
}

theme_spatial <- function(base_size = 12.5, base_family = "sans") {
  ggplot2::theme_void(base_size = base_size, base_family = base_family) +
  ggplot2::theme(
    plot.title = element_text(face = "bold", hjust = 0.5, size = base_size + 2.5, color = "black"),
    plot.subtitle = element_text(hjust = 0.5, size = base_size - 1, color = "black"),
    strip.text = element_text(face = "bold", size = base_size - 0.5, color = "black"),
    legend.title = element_text(face = "bold", size = base_size, color = "black"),
    legend.text = element_text(size = base_size - 1.5, color = "black"),
    legend.position = "right",
    plot.background = element_rect(fill = "white", color = NA)
  )
}

save_single_panel <- function(
  plot,
  figure,
  panel,
  width,
  height
) {
  base <- file.path(
    panel_figure_root,
    paste0(
      figure,
      "_",
      panel,
      ""
    )
  )

  ggplot2::ggsave(
    filename = paste0(
      base,
      ".pdf"
    ),
    plot = plot,
    width = width,
    height = height,
    units = "in",
    device = grDevices::cairo_pdf
  )

  ggplot2::ggsave(
    filename = paste0(
      base,
      ".jpg"
    ),
    plot = plot,
    width = width,
    height = height,
    units = "in",
    dpi = 300
  )
}

draw_plot_at <- function(
  plot,
  row,
  col,
  nrow,
  ncol
) {
  print(
    plot,
    vp = grid::viewport(
      layout.pos.row = row,
      layout.pos.col = col
    )
  )
}

save_grid_figure <- function(
  plots,
  positions,
  filename_stem,
  width,
  height,
  nrow,
  ncol,
  panel_labels = NULL,
  row_heights = rep(1, nrow),
  col_widths = rep(1, ncol)
) {
  if (length(row_heights) != nrow) {
    stop("row_heights must have length nrow.", call. = FALSE)
  }
  if (length(col_widths) != ncol) {
    stop("col_widths must have length ncol.", call. = FALSE)
  }

  render <- function() {
    grid::grid.newpage()
    grid::pushViewport(
      grid::viewport(
        layout = grid::grid.layout(
          nrow,
          ncol,
          heights = grid::unit(row_heights, "null"),
          widths = grid::unit(col_widths, "null")
        )
      )
    )

    for (
      i in seq_along(plots)
    ) {
      draw_plot_at(
        plots[[i]],
        positions[[i]][[1]],
        positions[[i]][[2]],
        nrow,
        ncol
      )
    }
  }

  pdf_file <- file.path(
    figure_root,
    paste0(
      filename_stem,
      ".pdf"
    )
  )

  jpg_file <- file.path(
    figure_root,
    paste0(
      filename_stem,
      ".jpg"
    )
  )

  grDevices::cairo_pdf(
    pdf_file,
    width = width,
    height = height
  )
  render()
  grDevices::dev.off()

  grDevices::jpeg(
    jpg_file,
    width = width,
    height = height,
    units = "in",
    res = 300,
    quality = 100
  )
  render()
  grDevices::dev.off()
}

assert_columns <- function(df, cols, label) {
  miss <- setdiff(
    cols,
    colnames(df)
  )

  if (length(miss) > 0L) {
    stop(
      label,
      " missing columns: ",
      paste(
        miss,
        collapse = ", "
      ),
      call. = FALSE
    )
  }
}


############################################################
## 1B. Publication display labels
##     Reporting-only aliases; underlying data are unchanged.
############################################################

state_display <- c(
  Immune_defective_Cold = "immune-defective/cold",
  Melanocytic_Differentiation = "melanocytic differentiation",
  Myeloid_Treg_Immunosuppressive = "myeloid–Treg immunosuppressive",
  Tumor_dedifferentiation_Stromal_remodeling =
    "tumor-dedifferentiation/stromal-remodeling"
)

method_display <- c(
  Raw = "raw",
  QC_residualized = "qc-adjusted",
  Composition_residualized = "composition-adjusted",
  QC_Composition_residualized = "qc + composition-adjusted"
)

composition_display <- c(
  B_Plasma = "B/plasma",
  CAF_Stromal = "CAF/stromal",
  Endothelial = "Endothelial",
  Melanoma_Lineage = "Melanoma-lineage",
  Myeloid = "Myeloid",
  T_NK = "T/NK"
)

cutoff_display <- c(
  top15 = "top 15%",
  top20 = "top 20%",
  top25 = "top 25%",
  top30 = "top 30%",
  top35 = "top 35%",
  median = "median",
  z_gt_0 = "z > 0"
)

null_display <- c(
  CAF_Endothelial_joint_quartile_stratified =
    "CAF/stromal × endothelial-stratified",
  Unrestricted = "Unrestricted"
)

map_labels <- function(x, mapping) {
  x_chr <- as.character(x)
  hit <- x_chr %in% names(mapping)
  x_chr[hit] <- unname(mapping[x_chr[hit]])
  x_chr
}


## Reporting-only line wrapping for long manuscript-facing labels.
## Underlying analytical values/factors are NOT changed.
wrap_public_label <- function(x) {
  y <- as.character(x)

  ## Long derived dual-high category: use three semantic lines.
  y[y %in% c(
    "tumor-dedifferentiation/stromal-remodeling high only",
    "tumor-dedifferentiation/stromal-remodeling-high only",
    "Tumor-dedifferentiation/Stromal-remodeling high only",
    "Dediff/Stromal high only",
    "Dediff/Stromal-High Only"
  )] <- "tumor-dedifferentiation/\nstromal-remodeling\nhigh only"

  ## Long primary state: break at the biologically meaningful slash.
  y[y %in% c(
    "tumor-dedifferentiation/stromal-remodeling",
    "Tumor-dedifferentiation/Stromal-remodeling"
  )] <- "tumor-dedifferentiation/\nstromal-remodeling"

  ## Myeloid–Treg labels are wrapped only where panel width is constrained.
  y[y %in% c(
    "myeloid–Treg immunosuppressive",
    "myeloid-Treg immunosuppressive",
    "Myeloid–Treg Immunosuppressive",
    "Myeloid-Treg Immunosuppressive"
  )] <- "myeloid–Treg\nimmunosuppressive"

  y[y %in% c(
    "myeloid–Treg high only",
    "myeloid-Treg high only",
    "myeloid–Treg-high only",
    "myeloid-Treg-high only",
    "Myeloid–Treg high only",
    "Myeloid-Treg high only"
  )] <- "myeloid–Treg\nhigh only"

  y
}

## Compact manuscript-facing labels for dense four-category panels.
## DISPLAY ONLY: the underlying analytical Category values are unchanged.
compact_category_label <- function(x) {
  raw <- as.character(x)

  key <- raw
  key <- gsub("[\u2010\u2011\u2012\u2013\u2014\u2212]", "-", key, perl = TRUE)
  key <- tolower(trimws(key))
  key <- gsub("\\s+", " ", key, perl = TRUE)

  out <- raw

  out[key %in% c(
    "both high",
    "both-high",
    "dual-high",
    "dual high"
  )] <- "Both high"

  out[
    grepl("^myeloid-treg.*high only$", key) |
      key %in% c("myeloid-treg-high only")
  ] <- "Myeloid–Treg\nhigh only"

  out[key %in% c(
    "neither high",
    "neither-high"
  )] <- "Neither high"

  out[
    grepl("^tumor-dedifferentiation/stromal-remodeling.*high only$", key) |
      grepl("^tumor-dediff\\.?/stromal-remodeling.*high only$", key) |
      grepl("^dediff/stromal.*high only$", key)
  ] <- "Tumor-dediff./stromal-remodeling\nhigh only"

  out
}

compact_category_levels <- c(
  "Both high",
  "Myeloid–Treg\nhigh only",
  "Neither high",
  "Tumor-dediff./stromal-remodeling\nhigh only"
)

############################################################
## 2. 21D reporting readiness hard gate
############################################################

if (!file.exists(decision_file)) {
  stop(
    "Missing 21D reporting decision: ",
    decision_file,
    call. = FALSE
  )
}

decision <- read_csv_exact(
  decision_file
)

status_row <- decision[
  decision$Item ==
    "ReportingRebuildStatus",
  ,
  drop = FALSE
]

if (
  nrow(status_row) != 1L ||
  status_row$Value[[1]] !=
    "S15_S19_PANEL_SOURCES_READY_FOR_REPORTING_REBUILD"
) {
  stop(
    "21D reporting source contract is not fully closed. Current status: ",
    paste(
      status_row$Value,
      collapse = "; "
    ),
    call. = FALSE
  )
}

############################################################
## 3. Load canonical panel sources
############################################################

pf <- function(fig, file) {
  file.path(
    panel_root,
    fig,
    file
  )
}

## S15
s15a <- read_csv_exact(
  pf(
    "S15",
    "21_S15A_dominant_state_spatial_map.csv"
  )
)
s15b <- read_csv_exact(
  pf(
    "S15",
    "21_S15B_corrected_univariate_Moran_raw_QC_k6.csv"
  )
)
s15c <- read_csv_exact(
  pf(
    "S15",
    "21_S15C_corrected_high_state_neighbor_OR_DESCRIPTIVE.csv"
  )
)

## S16
s16a <- read_csv_exact(
  pf(
    "S16",
    "21_S16A_continuous_primary_pair_spot_scores.csv"
  )
)
s16a_summary <- read_csv_exact(
  pf(
    "S16",
    "21_S16A_continuous_primary_pair_summary.csv"
  )
)
s16b <- read_csv_exact(
  pf(
    "S16",
    "21_S16B_symmetric_bivariate_Moran_k4_k6_k8_k12.csv"
  )
)
s16c <- read_csv_exact(
  pf(
    "S16",
    "21_S16C_threshold_grid_dual_high_OR_DESCRIPTIVE.csv"
  )
)

## S17
s17a <- read_csv_exact(
  pf(
    "S17",
    "21_S17A_composition_modules_by_raw_category_long.csv"
  )
)
s17b <- read_csv_exact(
  pf(
    "S17",
    "21_S17B_state_composition_Spearman.csv"
  )
)
s17c <- read_csv_exact(
  pf(
    "S17",
    "21_S17C_raw_residualized_top25_Fisher_OR_DESCRIPTIVE.csv"
  )
)
s17d <- read_csv_exact(
  pf(
    "S17",
    "21_S17D_raw_vs_QCcomposition_spatial_categories.csv"
  )
)

## S18
s18a <- read_csv_exact(
  pf(
    "S18",
    "21_S18A_state_composition_Spearman.csv"
  )
)
s18b <- read_csv_exact(
  pf(
    "S18",
    "21_S18B_raw_residualized_primary_pair_Spearman.csv"
  )
)
s18c <- read_csv_exact(
  pf(
    "S18",
    "21_S18C_top25_dual_high_OR_and_permutation.csv"
  )
)
s18d <- read_csv_exact(
  pf(
    "S18",
    "21_S18D_bivariate_Moran_and_permutation_k6.csv"
  )
)

## S19
s19a <- read_csv_exact(
  pf(
    "S19",
    "21_S19A_humoral_TLS_modules_by_raw_category_long.csv"
  )
)
s19b <- read_csv_exact(
  pf(
    "S19",
    "21_S19B_humoral_TLS_module_spatial_scores_long.csv"
  )
)
s19c <- read_csv_exact(
  pf(
    "S19",
    "21_S19C_humoral_TLS_module_spatial_autocorrelation_k_sensitivity.csv"
  )
)
s19d <- read_csv_exact(
  pf(
    "S19",
    "21_S19D_operational_humoral_TLS_cohigh_features.csv"
  )
)



state_colors_public <- c(
  "immune-defective/cold" = "#4DBBD5",
  "myeloid–Treg immunosuppressive" = "#00A087",
  "tumor-dedifferentiation/stromal-remodeling" = "#E64B35",
  "melanocytic differentiation" = "#3C5488"
)

if ("DominantState" %in% colnames(s15a)) {
  s15a$DominantState <- map_labels(s15a$DominantState, state_display)
}

############################################################
## 3B. Apply publication display labels
############################################################

if ("State" %in% colnames(s15b)) {
  s15b$State <- map_labels(
    s15b$State,
    state_display
  )
}
if ("State" %in% colnames(s15c)) {
  s15c$State <- map_labels(
    s15c$State,
    state_display
  )
}
if ("ScoreType" %in% colnames(s15b)) {
  s15b$ScoreType <- map_labels(
    s15b$ScoreType,
    c(
      Raw = "raw",
      QC_residualized = "qc-adjusted"
    )
  )
}
if ("CutoffName" %in% colnames(s16c)) {
  s16c$CutoffName <- map_labels(
    s16c$CutoffName,
    cutoff_display
  )
}

for (obj_name in c("s17a", "s17b", "s18a")) {
  obj <- get(obj_name)
  if ("Module" %in% colnames(obj)) {
    obj$Module <- map_labels(
      obj$Module,
      composition_display
    )
  }
  if ("State" %in% colnames(obj)) {
    obj$State <- map_labels(
      obj$State,
      state_display
    )
  }
  assign(
    obj_name,
    obj
  )
}

for (obj_name in c("s17c", "s17d", "s18b", "s18c", "s18d")) {
  obj <- get(obj_name)
  if ("Method" %in% colnames(obj)) {
    obj$Method <- map_labels(
      obj$Method,
      method_display
    )
  }
  assign(
    obj_name,
    obj
  )
}

for (obj_name in c("s18c", "s18d")) {
  obj <- get(obj_name)
  if ("Null" %in% colnames(obj)) {
    obj$Null <- map_labels(
      obj$Null,
      null_display
    )
  }
  assign(
    obj_name,
    obj
  )
}

############################################################
## 4. Figure S15
############################################################

assert_columns(
  s15a,
  c(
    "DisplayX",
    "DisplayY",
    "DominantState"
  ),
  "S15A"
)

p15a <- ggplot(
  s15a,
  aes(
    x = DisplayX,
    y = DisplayY,
    colour = DominantState
  )
) +
  geom_point(
    size = 0.9,
    alpha = 0.95
  ) +
  coord_fixed() +
  scale_y_reverse() +
  scale_colour_manual(
    values = state_colors_public,
    drop = FALSE,
    labels = wrap_public_label
  ) +
  labs(
    title = "A  Dominant transcriptional state",
    colour = "Dominant state"
  ) +
  theme_spatial()

assert_columns(
  s15b,
  c(
    "State",
    "ScoreType",
    "Moran_I",
    "p_empirical_two_sided",
    "n_perm"
  ),
  "S15B"
)

s15b$ScoreType <- factor(
  s15b$ScoreType,
  levels = c(
    "raw",
    "qc-adjusted"
  )
)

p15b <- ggplot(
  s15b,
  aes(
    x = State,
    y = Moran_I,
    group = ScoreType,
    shape = ScoreType
  )
) +
  geom_point(
    size = 3,
    position = position_dodge(
      width = 0.35
    )
  ) +
  coord_cartesian(
    ylim = c(
      0,
      1
    )
  ) +
  scale_x_discrete(
    labels = wrap_public_label
  ) +
  labs(
    title = "B  Spatial autocorrelation after graph correction",
    subtitle = "Direct FNN kNN, k=6; 999 two-sided permutations",
    x = NULL,
    y = "Moran-type I",
    shape = "Score"
  ) +
  theme_visium() +
  theme(
    axis.text.x = element_text(
      angle = 20,
      hjust = 1,
      size = 10.75,
      lineheight = 0.92
    )
  )

assert_columns(
  s15c,
  c(
    "State",
    "OR",
    "CI_low",
    "CI_high"
  ),
  "S15C"
)

p15c <- ggplot(
  s15c,
  aes(
    x = OR,
    y = reorder(
      State,
      OR
    )
  )
) +
  geom_vline(
    xintercept = 1,
    linetype = 2
  ) +
  geom_errorbar(
    aes(
      xmin = CI_low,
      xmax = CI_high
    ),
    orientation = "y",
    width = 0.18
  ) +
  geom_point(
    size = 2.8
  ) +
  scale_x_log10() +
  scale_y_discrete(
    labels = wrap_public_label
  ) +
  labs(
    title = "C  High-state neighbor enrichment",
    subtitle = "Descriptive edge-level effect size; Fisher P is not the primary spatial inference",
    x = "Odds ratio (log scale)",
    y = NULL
  ) +
  theme_visium() +
  theme(
    plot.subtitle = element_text(size = 10.75),
    axis.text.y = element_text(lineheight = 0.92)
  )

save_single_panel(
  p15a,
  "S15",
  "A",
  6.2,
  5.4
)
save_single_panel(
  p15b,
  "S15",
  "B",
  7.2,
  5.4
)
save_single_panel(
  p15c,
  "S15",
  "C",
  6.2,
  5.4
)

save_grid_figure(
  list(
    p15a,
    p15b,
    p15c
  ),
  list(
    c(
      1,
      1
    ),
    c(
      1,
      2
    ),
    c(
      2,
      1
    )
  ),
  "Supplementary_Figure_S15",
  width = 13,
  height = 11,
  nrow = 2,
  ncol = 2
)

############################################################
## 5. Figure S16
############################################################

assert_columns(
  s16a,
  c(
    "MyeloidTreg",
    "TumorStromal"
  ),
  "S16A"
)

raw_rho <- s16a_summary$estimate[
  s16a_summary$Analysis ==
    "Raw Spearman"
]

qc_rho <- s16a_summary$estimate[
  s16a_summary$Analysis ==
    "QC-adjusted partial Spearman"
]

subtitle16a <- paste0(
  "Raw Spearman \u03c1 = ",
  sprintf(
    "%.3f",
    raw_rho[[1]]
  ),
  "; QC-adjusted partial \u03c1 = ",
  sprintf(
    "%.3f",
    qc_rho[[1]]
  ),
  ". Effect-size summaries."
)

p16a <- ggplot(
  s16a,
  aes(
    x = MyeloidTreg,
    y = TumorStromal
  )
) +
  geom_point(
    size = 0.7,
    alpha = 0.35
  ) +
  geom_smooth(
    method = "lm",
    se = FALSE,
    linewidth = 0.7
  ) +
  labs(
    title = "A  Continuous primary-pair association",
    subtitle = subtitle16a,
    x = "myeloid–Treg immunosuppressive score",
    y = "tumor-dedifferentiation/\nstromal-remodeling score"
  ) +
  theme_visium() +
  theme(plot.subtitle = element_text(size = 10.75))

assert_columns(
  s16b,
  c(
    "k",
    "I_symmetric",
    "p_greater",
    "n_perm"
  ),
  "S16B"
)

p16b <- ggplot(
  s16b,
  aes(
    x = k,
    y = I_symmetric
  )
) +
  geom_line() +
  geom_point(
    size = 3
  ) +
  scale_x_continuous(
    breaks = sort(
      unique(
        s16b$k
      )
    )
  ) +
  labs(
    title = "B  Symmetric bivariate Moran-type statistic",
    subtitle = "Correct direct FNN graph; hardened single-y permutation null",
    x = "k nearest neighbors",
    y = expression(
      I[sym]
    )
  ) +
  theme_visium()

assert_columns(
  s16c,
  c(
    "CutoffName",
    "OR",
    "CI_low",
    "CI_high"
  ),
  "S16C"
)

s16c$CutoffName <- factor(
  s16c$CutoffName,
  levels = s16c$CutoffName
)

p16c <- ggplot(
  s16c,
  aes(
    x = CutoffName,
    y = OR,
    group = 1
  )
) +
  geom_hline(
    yintercept = 1,
    linetype = 2
  ) +
  geom_errorbar(
    aes(
      ymin = CI_low,
      ymax = CI_high
    ),
    width = 0.15
  ) +
  geom_line() +
  geom_point(
    size = 2.8
  ) +
  scale_y_log10() +
  labs(
    title = "C  Threshold sensitivity",
    subtitle = "Dual-high Fisher OR shown descriptively across prespecified cutoffs",
    x = "High-score definition",
    y = "Odds ratio (log scale)"
  ) +
  theme_visium() +
  theme(
    axis.text.x = element_text(
      angle = 25,
      hjust = 1,
      size = 10.75
    )
  )

save_single_panel(
  p16a,
  "S16",
  "A",
  6.4,
  5.4
)
save_single_panel(
  p16b,
  "S16",
  "B",
  5.8,
  5.0
)
save_single_panel(
  p16c,
  "S16",
  "C",
  6.2,
  5.0
)

save_grid_figure(
  list(
    p16a,
    p16b,
    p16c
  ),
  list(
    c(
      1,
      1
    ),
    c(
      1,
      2
    ),
    c(
      2,
      1
    )
  ),
  "Supplementary_Figure_S16",
  width = 13,
  height = 11,
  nrow = 2,
  ncol = 2
)

############################################################
## 6. Figure S17
############################################################

assert_columns(
  s17a,
  c(
    "Category",
    "Module",
    "Score"
  ),
  "S17A"
)

s17a$CategoryDisplay <- factor(
  compact_category_label(s17a$Category),
  levels = compact_category_levels
)

p17a <- ggplot(
  s17a,
  aes(
    x = CategoryDisplay,
    y = Score
  )
) +
  geom_boxplot(
    outlier.shape = NA,
    linewidth = 0.4
  ) +
  facet_wrap(
    ~ Module,
    scales = "free_y",
    ncol = 3
  ) +
  scale_x_discrete(
    drop = FALSE
  ) +
  labs(
    title = "A  Tissue-composition modules across raw dual-high categories",
    subtitle = "Descriptive context only",
    x = NULL,
    y = "Module score"
  ) +
  theme_visium(
    base_size = 11.5
  ) +
  theme(
    axis.text.x = element_text(
      angle = 25,
      hjust = 1,
      vjust = 1,
      size = 8.25,
      lineheight = 0.76,
      margin = margin(t = 2)
    ),
    plot.margin = margin(6, 6, 14, 6)
  )

assert_columns(
  s17b,
  c(
    "State",
    "Module",
    "rho"
  ),
  "S17B"
)

p17b <- ggplot(
  s17b,
  aes(
    x = Module,
    y = State,
    fill = rho
  )
) +
  geom_tile() +
  geom_text(
    aes(
      label = sprintf(
        "%.2f",
        rho
      )
    ),
    size = 3
  ) +
  scale_fill_gradient2(
    midpoint = 0
  ) +
  scale_y_discrete(
    labels = wrap_public_label
  ) +
  labs(
    title = "B  State–composition association",
    subtitle = "Spearman \u03c1; descriptive spot-level association",
    x = NULL,
    y = NULL,
    fill = "\u03c1"
  ) +
  theme_visium(
    base_size = 11.5
  ) +
  theme(
    axis.text.x = element_text(
      angle = 30,
      hjust = 1,
      size = 10.25
    ),
    axis.text.y = element_text(
      lineheight = 0.92
    )
  )

assert_columns(
  s17c,
  c(
    "Method",
    "OR",
    "CI_low",
    "CI_high"
  ),
  "S17C"
)

method_levels <- c(
  "raw",
  "qc-adjusted",
  "composition-adjusted",
  "qc + composition-adjusted"
)

s17c$Method <- factor(
  s17c$Method,
  levels = method_levels
)

p17c <- ggplot(
  s17c,
  aes(
    x = OR,
    y = Method
  )
) +
  geom_vline(
    xintercept = 1,
    linetype = 2
  ) +
  geom_errorbar(
    aes(
      xmin = CI_low,
      xmax = CI_high
    ),
    orientation = "y",
    width = 0.18
  ) +
  geom_point(
    size = 3
  ) +
  scale_x_log10() +
  labs(
    title = "C  Dual-high enrichment after residualization",
    subtitle = "Fisher OR is a descriptive effect-size summary",
    x = "Odds ratio (log scale)",
    y = NULL
  ) +
  theme_visium()

assert_columns(
  s17d,
  c(
    "DisplayX",
    "DisplayY",
    "Method",
    "Category"
  ),
  "S17D"
)

p17d <- ggplot(
  s17d,
  aes(
    x = DisplayX,
    y = DisplayY,
    colour = Category
  )
) +
  geom_point(
    size = 0.7,
    alpha = 0.9
  ) +
  coord_fixed() +
  scale_y_reverse() +
  scale_colour_discrete(
    labels = compact_category_label
  ) +
  facet_wrap(
    ~ Method,
    nrow = 1
  ) +
  labs(
    title = "D  Raw versus QC+composition-adjusted\noperational categories",
    colour = "Category"
  ) +
  theme_spatial(
    base_size = 11.5
  ) +
  theme(
    plot.title = element_text(
      size = 13.0,
      lineheight = 0.92,
      hjust = 0.5
    ),
    legend.title = element_text(
      size = 10.25,
      face = "bold"
    ),
    legend.text = element_text(
      size = 8.25,
      lineheight = 0.76
    ),
    legend.key.height = grid::unit(0.38, "cm"),
    legend.spacing.y = grid::unit(0.01, "cm"),
    plot.margin = margin(8, 8, 6, 10)
  )

for (
  obj in list(
    list(
      p = p17a,
      panel = "A",
      w = 8,
      h = 6.5
    ),
    list(
      p = p17b,
      panel = "B",
      w = 7.5,
      h = 5.5
    ),
    list(
      p = p17c,
      panel = "C",
      w = 6.2,
      h = 5.0
    ),
    list(
      p = p17d,
      panel = "D",
      w = 8.4,
      h = 4.5
    )
  )
) {
  save_single_panel(
    obj$p,
    "S17",
    obj$panel,
    obj$w,
    obj$h
  )
}

save_grid_figure(
  list(
    p17a,
    p17b,
    p17c,
    p17d
  ),
  list(
    c(
      1,
      1
    ),
    c(
      1,
      2
    ),
    c(
      2,
      1
    ),
    c(
      2,
      2
    )
  ),
  "Supplementary_Figure_S17",
  width = 15,
  height = 12,
  nrow = 2,
  ncol = 2,
  row_heights = c(1.10, 0.90)
)

############################################################
## 7. Figure S18
############################################################

p18a <- ggplot(
  s18a,
  aes(
    x = Module,
    y = State,
    fill = rho
  )
) +
  geom_tile() +
  geom_text(
    aes(
      label = sprintf(
        "%.2f",
        rho
      )
    ),
    size = 3
  ) +
  scale_fill_gradient2(
    midpoint = 0
  ) +
  scale_y_discrete(
    labels = wrap_public_label
  ) +
  labs(
    title = "A  State–composition association",
    subtitle = "Context panel; not independent evidence",
    x = NULL,
    y = NULL,
    fill = "\u03c1"
  ) +
  theme_visium(
    base_size = 11.5
  ) +
  theme(
    axis.text.x = element_text(
      angle = 30,
      hjust = 1,
      size = 10.25
    ),
    axis.text.y = element_text(
      lineheight = 0.92
    )
  )

assert_columns(
  s18b,
  c(
    "Method",
    "rho"
  ),
  "S18B"
)

s18b$Method <- factor(
  s18b$Method,
  levels = method_levels
)

p18b <- ggplot(
  s18b,
  aes(
    x = Method,
    y = rho,
    group = 1
  )
) +
  geom_hline(
    yintercept = 0,
    linetype = 2
  ) +
  geom_line() +
  geom_point(
    size = 3
  ) +
  labs(
    title = "B  Primary-pair association after adjustment",
    subtitle = "Spearman \u03c1 shown as an effect-size summary",
    x = NULL,
    y = "Spearman \u03c1"
  ) +
  theme_visium() +
  theme(
    axis.text.x = element_text(
      angle = 25,
      hjust = 1,
      size = 10.75
    )
  )

assert_columns(
  s18c,
  c(
    "Method",
    "Null",
    "BothHigh",
    "permutation_mean",
    "p_overlap_greater"
  ),
  "S18C"
)

s18c$Method <- factor(
  s18c$Method,
  levels = method_levels
)

p18c <- ggplot(
  s18c,
  aes(
    x = Method,
    y = BothHigh
  )
) +
  geom_point(
    size = 3.2
  ) +
  geom_point(
    aes(
      y = permutation_mean,
      shape = Null
    ),
    size = 2.8
  ) +
  geom_segment(
    aes(
      xend = Method,
      y = permutation_mean,
      yend = BothHigh,
      linetype = Null
    ),
    linewidth = 0.5
  ) +
  labs(
    title = "C  Top-quartile co-high overlap\nversus permutation expectation",
    subtitle = "Observed count versus unrestricted and composition-stratified null means",
    x = NULL,
    y = "Both-high spots",
    shape = "Null",
    linetype = "Null"
  ) +
  theme_visium(
    base_size = 11.5
  ) +
  theme(
    plot.title = element_text(
      lineheight = 0.92
    ),
    axis.text.x = element_text(
      angle = 25,
      hjust = 1,
      size = 10.75
    )
  )

assert_columns(
  s18d,
  c(
    "Method",
    "Null",
    "I_symmetric",
    "perm_mean",
    "p_greater",
    "n_perm"
  ),
  "S18D"
)

s18d$Method <- factor(
  s18d$Method,
  levels = method_levels
)

p18d <- ggplot(
  s18d,
  aes(
    x = Method,
    y = I_symmetric
  )
) +
  geom_hline(
    yintercept = 0,
    linetype = 2
  ) +
  geom_point(
    size = 3.2
  ) +
  geom_point(
    aes(
      y = perm_mean,
      shape = Null
    ),
    size = 2.8
  ) +
  geom_segment(
    aes(
      xend = Method,
      y = perm_mean,
      yend = I_symmetric,
      linetype = Null
    ),
    linewidth = 0.5
  ) +
  labs(
    title = "D  Composition-aware spatial co-variation",
    subtitle = "Observed symmetric Moran-type statistic versus null expectation;\nempirical P from 999 permutations",
    x = NULL,
    y = expression(
      I[sym]
    ),
    shape = "Null",
    linetype = "Null"
  ) +
  theme_visium(
    base_size = 11.5
  ) +
  theme(
    axis.text.x = element_text(
      angle = 25,
      hjust = 1,
      size = 10.75
    )
  )

for (
  obj in list(
    list(
      p = p18a,
      panel = "A",
      w = 7.5,
      h = 5.5
    ),
    list(
      p = p18b,
      panel = "B",
      w = 6.2,
      h = 5.0
    ),
    list(
      p = p18c,
      panel = "C",
      w = 7.2,
      h = 5.5
    ),
    list(
      p = p18d,
      panel = "D",
      w = 7.2,
      h = 5.5
    )
  )
) {
  save_single_panel(
    obj$p,
    "S18",
    obj$panel,
    obj$w,
    obj$h
  )
}

save_grid_figure(
  list(
    p18a,
    p18b,
    p18c,
    p18d
  ),
  list(
    c(
      1,
      1
    ),
    c(
      1,
      2
    ),
    c(
      2,
      1
    ),
    c(
      2,
      2
    )
  ),
  "Supplementary_Figure_S18",
  width = 15,
  height = 12,
  nrow = 2,
  ncol = 2
)

############################################################
## 8. Figure S19
############################################################

assert_columns(
  s19a,
  c(
    "Category",
    "Module",
    "Score"
  ),
  "S19A"
)

s19a$CategoryDisplay <- factor(
  compact_category_label(s19a$Category),
  levels = compact_category_levels
)

p19a <- ggplot(
  s19a,
  aes(
    x = CategoryDisplay,
    y = Score
  )
) +
  geom_boxplot(
    outlier.shape = NA,
    linewidth = 0.4
  ) +
  facet_wrap(
    ~ Module,
    scales = "free_y",
    ncol = 3
  ) +
  scale_x_discrete(
    drop = FALSE
  ) +
  labs(
    title = "A  Humoral/TLS-like transcriptional modules by raw category",
    subtitle = "Descriptive transcriptional context; not mature TLS calling",
    x = NULL,
    y = "Module score"
  ) +
  theme_visium(
    base_size = 11.5
  ) +
  theme(
    axis.text.x = element_text(
      angle = 25,
      hjust = 1,
      vjust = 1,
      size = 8.25,
      lineheight = 0.76,
      margin = margin(t = 2)
    ),
    plot.margin = margin(6, 6, 14, 6)
  )

assert_columns(
  s19b,
  c(
    "SpatialX",
    "SpatialY",
    "Module",
    "Score"
  ),
  "S19B"
)

p19b <- ggplot(
  s19b,
  aes(
    x = SpatialX,
    y = SpatialY,
    colour = Score
  )
) +
  geom_point(
    size = 0.45
  ) +
  coord_fixed() +
  scale_y_reverse() +
  facet_wrap(
    ~ Module,
    ncol = 4
  ) +
  scale_colour_gradient2(
    midpoint = 0
  ) +
  labs(
    title = "B  Spatial distribution of humoral/TLS-like transcriptional modules",
    subtitle = "Descriptive maps; no architectural or functional TLS inference",
    colour = "Score"
  ) +
  theme_spatial(
    base_size = 11.0
  )

assert_columns(
  s19c,
  c(
    "Module",
    "k",
    "SpatialAutocorrelation"
  ),
  "S19C"
)

p19c <- ggplot(
  s19c,
  aes(
    x = k,
    y = SpatialAutocorrelation
  )
) +
  geom_hline(
    yintercept = 0,
    linetype = 2
  ) +
  geom_line() +
  geom_point(
    size = 2.2
  ) +
  facet_wrap(
    ~ Module,
    ncol = 2
  ) +
  scale_x_continuous(
    breaks = sort(
      unique(
        s19c$k
      )
    )
  ) +
  labs(
    title = "C  Spatial autocorrelation sensitivity of humoral/TLS-like modules",
    subtitle = "Direct FNN kNN; descriptive only, without unsupported permutation claims",
    x = "k nearest neighbors",
    y = "Spatial autocorrelation"
  ) +
  theme_visium(
    base_size = 11.5
  )

assert_columns(
  s19d,
  c(
    "SpatialX",
    "SpatialY",
    "Feature"
  ),
  "S19D"
)

p19d <- ggplot(
  s19d,
  aes(
    x = SpatialX,
    y = SpatialY,
    colour = Feature
  )
) +
  geom_point(
    size = 0.7,
    alpha = 0.9
  ) +
  coord_fixed() +
  scale_y_reverse() +
  labs(
    title = "D  Operational humoral/TLS-like co-high contexts",
    subtitle = "Operational transcriptional context only; not mature TLS,\ngerminal-center architecture, or functional TLS",
    colour = "Operational feature"
  ) +
  theme_spatial(
    base_size = 11.0
  )

for (
  obj in list(
    list(
      p = p19a,
      panel = "A",
      w = 8.5,
      h = 6.5
    ),
    list(
      p = p19b,
      panel = "B",
      w = 10.0,
      h = 7.5
    ),
    list(
      p = p19c,
      panel = "C",
      w = 7.8,
      h = 5.5
    ),
    list(
      p = p19d,
      panel = "D",
      w = 7.2,
      h = 5.5
    )
  )
) {
  save_single_panel(
    obj$p,
    "S19",
    obj$panel,
    obj$w,
    obj$h
  )
}

save_grid_figure(
  list(
    p19a,
    p19b,
    p19c,
    p19d
  ),
  list(
    c(
      1,
      1
    ),
    c(
      1,
      2
    ),
    c(
      2,
      1
    ),
    c(
      2,
      2
    )
  ),
  "Supplementary_Figure_S19",
  width = 17,
  height = 13.5,
  nrow = 2,
  ncol = 2,
  row_heights = c(1.08, 0.92)
)

############################################################
## 9. Reporting output manifest
############################################################

figure_files <- list.files(
  figure_root,
  pattern = "\\.(pdf|jpg)$",
  recursive = TRUE,
  full.names = TRUE,
  ignore.case = TRUE
)

manifest <- data.frame(
  File = basename(
    figure_files
  ),
  Path = normalizePath(
    figure_files,
    winslash = "/",
    mustWork = FALSE
  ),
  SizeBytes = file.info(
    figure_files
  )$size,
  MD5 = unname(
    tools::md5sum(
      figure_files
    )
  ),
  stringsAsFactors = FALSE
)

utils::write.csv(
  manifest,
  file.path(
    reporting_root,
    "22_S15_S19_figure_manifest.csv"
  ),
  row.names = FALSE,
  na = ""
)

############################################################
## 10. Reporting gates
############################################################

expected_stems <- paste0(
  "Supplementary_Figure_S",
  15:19,
  ""
)

report_gates <- do.call(
  rbind,
  lapply(
    expected_stems,
    function(stem) {
      pdf_file <- file.path(
        figure_root,
        paste0(
          stem,
          ".pdf"
        )
      )

      jpg_file <- file.path(
        figure_root,
        paste0(
          stem,
          ".jpg"
        )
      )

      data.frame(
        Figure = stem,
        PDF_exists = file.exists(
          pdf_file
        ),
        JPG_exists = file.exists(
          jpg_file
        ),
        PDF_nonempty =
          file.exists(
            pdf_file
          ) &&
          file.info(
            pdf_file
          )$size >
          1000,
        JPG_nonempty =
          file.exists(
            jpg_file
          ) &&
          file.info(
            jpg_file
          )$size >
          1000,
        Pass =
          file.exists(
            pdf_file
          ) &&
          file.exists(
            jpg_file
          ) &&
          file.info(
            pdf_file
          )$size >
          1000 &&
          file.info(
            jpg_file
          )$size >
          1000,
        stringsAsFactors = FALSE
      )
    }
  )
)

utils::write.csv(
  report_gates,
  file.path(
    reporting_root,
    "22_S15_S19_reporting_gates.csv"
  ),
  row.names = FALSE,
  na = ""
)

blocking_fail <- sum(
  !report_gates$Pass
)

status <- if (
  blocking_fail == 0L
) {
  "S15_S19_REPORTING_REBUILD_PASS_PENDING_VISUAL_QC"
} else {
  "S15_S19_REPORTING_REBUILD_BLOCKED"
}

decision_out <- data.frame(
  Item = c(
    "FiguresExpected",
    "FiguresPassingFileGates",
    "BlockingReportingFailures",
    "ReportingStatus"
  ),
  Value = c(
    nrow(
      report_gates
    ),
    sum(
      report_gates$Pass
    ),
    blocking_fail,
    status
  ),
  stringsAsFactors = FALSE
)

utils::write.csv(
  decision_out,
  file.path(
    reporting_root,
    "22_S15_S19_reporting_decision.csv"
  ),
  row.names = FALSE,
  na = ""
)

cat("\n============================================================\n")
cat("S15-S19 REPORTING REBUILD COMPLETED\n")
cat("============================================================\n")
cat("Figures passing file gates: ", sum(report_gates$Pass), "/5\n", sep = "")
cat("Blocking reporting failures: ", blocking_fail, "\n", sep = "")
cat("Reporting status: ", status, "\n", sep = "")
cat("Output: ", normalizePath(figure_root, winslash = "/", mustWork = FALSE), "\n", sep = "")
cat("============================================================\n")

## Public sequential end gate
.step08_files <- file.path(figure_root, paste0("Supplementary_Figure_S", 15:19, ".pdf"))
if (any(!file.exists(.step08_files))) stop("STEP 08 missing final S15-S19 PDF(s): ", paste(.step08_files[!file.exists(.step08_files)], collapse = "\n"), call. = FALSE)
cat("\nSTEP 08 PASS — Supplementary Figures S15-S19 rebuilt: 5/5 PDF present\n")
